# Generated by Django 5.0.6 on 2024-07-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=2, max_length=10)),
                ('stock', models.PositiveIntegerField()),
                ('imagen', models.ImageField(default='productos/default.jpg', upload_to='productos/')),
            ],
        ),
    ]
